### ISSUE TITLE
Update Font sizes to help with accessibility char limit 

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#132]
styles.css

:root {

    --body-font-size-m: 24px;
    --body-font-size-s: 20px;
    --body-font-size-xs: 18px;
    --heading-font-size-xxl: 56px;
    --heading-font-size-xl: 32px;
    --heading-font-size-l: 28px;
    --heading-font-size-m: 24px;
    --heading-font-size-s: 20px;
    --heading-font-size-xs: 18px;

}

**Comment by janefrommaine** [comment]
Hi @sforschen,

I noticed that there are some font-sizes that are not covered in our variables:

registration-form - 27px
blog-feed - 15px
footer - 16px
table - 13px
footer - 12px

I'm planning to add some more items to our --body-font-size custom properties to cover more of these examples but also modify some to match to the closest variable value...

Current variables...
--body-font-size-m: 24px;
--body-font-size-s: 20px;
--body-font-size-xs: 18px;

Updated variables....
--body-font-size-xl: 24px;
--body-font-size-l: 20px;
--body-font-size-m: 18px;
--body-font-size-s: 16px;
--body-font-size-xs: 12px;

I'm also planning to keep the Top navigation and Breadcrumbs as 16px so that they still fit at smaller breakpoints.

**Comment by janefrommaine** [comment]
@sforschen, digging in to the fonts a little more I noticed that we aren't currently supporting Font Scaling. We do support the browser zoom, but we don't support if someone has set the base font size in their browser using something like Chrome > Settings > Appearance > Font Size (increase to Very Large).
To support this, we should switch from using px to rem when it comes to font sizes.

It might be good to make this change in this ticket because it will require testing a couple bunch of things.

**Comment by sforschen** [comment]
@janefrommaine I am all for moving to rem. I never realized that rem was related to someone's default browser font size, I thought it was nicer because you could set all the sizes based of the base rem.

**Comment by sforschen** [comment]
Should we update the rem to be base 16px and then do font sizes rem?

 html {
1rem = 16px 

--body-font-size-xl: 1.5rem;
--body-font-size-l: 1.25rem;
--body-font-size-m: 1.125rem;
--body-font-size-s: 1rem;
--body-font-size-xs: .75rem;
--heading-font-size-xxl: 3.5rem;
--heading-font-size-xl: 2rem;
--heading-font-size-l: 1.75rem;
--heading-font-size-m: 1.5rem;
--heading-font-size-s: 1.25rem;
--heading-font-size-xs: 1.125rem;
