### ISSUE TITLE
Design/CSS Changes

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#73]
In the attached document I highlighted the code in yellow where I am requesting fixes and highlighted in green are some commentary and some image examples. 

[Design-CSS changes.docx](https://github.com/hlxsites/elixirsolutions/files/11668210/Design-CSS.changes.docx)

**Comment by shsteimer** [comment]
want to talk through these.

There is a lot here and while you've included relevant CSS, concerned that if we simply copy/pasta it in, we may miss something, put something in the wrong place, etc. 


A PR might be the ideal way to do this, but since you've already documented it all here, perhaps we can do it together on a live session.
