### ISSUE TITLE
Plan Sponsors Hero portal selection label 

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#74]
Plan Sponsors
https://main--elixirsolutions--hlxsites.hlx.live/plansponsors 
 
Hero block
"Select your client portal" should be a <label> instead of <h5>
The label should have for="sponsor-selected" property tied to the select element

**Comment by sforschen** [comment]
I will defer to what you think is the best approach. I think we could simplify even more and just have the links rather than the dropdown and button as that would reduce the number of clicks and we have the room to do so.

**Comment by shsteimer** [comment]
@sforschen I'd love to get rid of the drop down entirely. It's essentially a one off used on one page (nothing makes me happier than deleting code).

@ddragosd does our hero support having more than one button in it? or is that something we'd need to add support for?

**Comment by ddragosd** [comment]
I very much like the idea of fewer clicks too ... and deleting code 👍 

@sforschen would it work to place the links to client portals right under the hero section, as 3 cards, instead of inside the Hero ? See this page as an example: https://main--elixirsolutions--hlxsites.hlx.page/drafts/plansponsors  

In this way we'd check both boxes 🎉 .  But feel free to suggest what you prefer.

**Comment by sforschen** [comment]
Do the cards work without images or does that leave an empty tag? If we can use it without images and it leaves us room to describe who should be using what portal it would work.

**Comment by sforschen** [comment]
@ddragosd This works really well, my only adjustment is getting rid of the min-height in the CSS for columns.  But otherwise I think this is a good solution.
