### ISSUE TITLE
Accessibility - Blog front page articles link 

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#79]
The focus and clickable areas of the blog post card are awkward.
The description text and Read more link be lumped under a hyperlink all together link the cards above it
![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/a7fabc27-3c93-4a9a-8cb5-fa1bdbe0f368)

**Comment by shsteimer** [comment]
This is somewhat by design. When you have "read more" links which lack additional description you get dinged on SEO for links not having descriptive text. You can see this on the page speed score of current site https://pagespeed.web.dev/analysis/https-www-elixirsolutions-com/oqggrm3l4c?form_factor=mobile

<img width="1030" alt="image" src="https://github.com/hlxsites/elixirsolutions/assets/1646396/49f41a83-e80b-444f-a41d-a2f29e677e0d">

happy to change this and it's an easy fix, but worth considering that as part of whatever final solution we decide on here.

**Comment by sforschen** [comment]
We will change all of these to be more descriptive which will help accessibility and SEO. I will send these to our writer to see if she can develop something better than what I currently have.  

As long as the functionality changes to match the other cards that will help satisfy the accessibility aspect.

**Comment by shsteimer** [comment]
OK. reason for this is because this is the same blog element as used on the /blog page, just with the tags hidden. since the tags themselves are links, I couldn't just wrap the whole card in one link and be done like we do with other cards.

I can make these 2 separate elements, and wrap the whole thing in one link to make it more similar to how the other cards work, but suspect there will be similar issues with the blog landing page, so this is probably worth a discussion.

**Comment by shsteimer** [comment]
made a [small css adjustment](https://github.com/hlxsites/elixirsolutions/commit/f0fe61082c88c5931b53a7ccc9326b5a232da309) so that the link is a block element and acts as one link rather than 2 elements linked. I think that may be all we need, but we can still discuss/look at this and decide on best solution
